server:
  servlet:
    context-path: /api


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    username: keycloak
    plataform: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        show_sql: true
      javax:
        persistence:
          query:
            timeout: 50
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/nosso-cartao}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/nosso-cartao/protocol/openid-connect/certs}

management:
  endpoints:
    web.exposure.include: info,health,prometheus
    prometheus.enabled: true
  metrics.tags:
    aplicacao: ${nome_da_aplicacao:serviço de proposta}
    ambiente: ${ambiente:desenvolvimento}



feign:
  client:
    config:
      default:
        connectTimeout: 100
        readTimeout: 100


periodicidade:
  busca-cartao: ${PERIODICIDADE_BUSCA_CARTAO:1000}

cartoes:
  host: ${CARTOES_URL:http://localhost:8888/api/cartoes}
solicitacao:
  host: ${ANALISE_URL:http://localhost:9999/api/solicitacao}